/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Availability {
  'id' : string,
  'startTime' : TimeOfDay,
  'isRecurring' : boolean,
  'endTime' : TimeOfDay,
  'dayOfWeek' : DayOfWeek,
  'blackoutDates' : Array<BlackoutDate>,
}
export interface BlackoutDate { 'end' : Time, 'start' : Time }
export interface Booking {
  'id' : string,
  'paymentStatus' : PaymentStatus,
  'clientName' : string,
  'sessionTime' : Time,
  'owner' : Principal,
  'clientEmail' : string,
  'bookingTime' : Time,
  'virtualMeetingLink' : [] | [string],
}
export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export type ExternalBlob = Uint8Array;
export interface FileReference { 'id' : string, 'blob' : ExternalBlob }
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : { 'sessionId' : string } } |
  { 'failed' : { 'error' : string } };
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TimeOfDay { 'hours' : bigint, 'minutes' : bigint }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[string], undefined>,
  'createBooking' : ActorMethod<[string, string, Time], string>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAvailableTimeSlots' : ActorMethod<[], Array<Availability>>,
  'getBooking' : ActorMethod<[string], Booking>,
  'getBookingsForClient' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFile' : ActorMethod<[string], FileReference>,
  'getFileList' : ActorMethod<[bigint, bigint], Array<FileReference>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAvailableTimeSlots' : ActorMethod<[Array<Availability>], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingPaymentStatus' : ActorMethod<
    [string, PaymentStatus],
    undefined
  >,
  'updateBookingWithVirtualMeetingLink' : ActorMethod<
    [string, string],
    undefined
  >,
  'uploadFile' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];